### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by TrySound** [ritz078/rollup-plugin-filesize#1]
- change `lodash` to something like [deep-assign](https://www.npmjs.com/package/deep-assign). lodash is too big module. I recommend to use more atomic modules.
- move options processing into the previous scope `filesize`. This will make code more compact and simple.
- Add a few test cases with different options. I recommend [ava](https://github.com/sindresorhus/ava) which has babel support out of the box.

**Comment by ritz078** [comment]
done

**Comment by TrySound** [comment]
@ritz078 Cool!
