### ISSUE TITLE
Chalk forced?

### ISSUE THREAD

**Issue by timdp** [ritz078/rollup-plugin-filesize#10]
Just wondering: is there a reason why you pass `enabled: true` to chalk? We run your code on a build server and it's the only thing that outputs color.

**Comment by ritz078** [comment]
AFAIR it didn't work if I did not set that. Do you have a better suggestion ?

**Comment by timdp** [comment]
I always just use `import chalk from 'chalk'`and let it autodetect support. It's worked fine so far and I imagine that's what most dependents do.

**Comment by ritz078** [comment]
I will check that and maybe provide this as an option.

**Comment by timdp** [comment]
I think npm itself has the same behavior. There's a `--color=always` flag that overrides it, but by default, it won't colorize unless it detects support for it.

**Comment by ritz078** [comment]
should be fixed with v1.0.1
