### ISSUE TITLE
Narrow down version of "colors" dependency

### ISSUE THREAD

**Issue by KebapBoy** [ritz078/rollup-plugin-filesize#105]
Due to [an issue](https://github.com/Marak/colors.js/issues/289) with the newest version of the [colors](https://github.com/Marak/colors.js) package it would be great if the dependency is not specified as `^1.4.0` but `1.4.0` instead so the broken package version `1.4.2` is not installed.

**Comment by ritz078** [comment]
Thanks for the heads up. A new patch has been released.
