### ISSUE TITLE
Source not up to date

### ISSUE THREAD

**Issue by hboomsma** [ritz078/rollup-plugin-filesize#14]
At least source for 1.3.1 is missing on github.

I was surprised when I found out this package was trying to get more stars through code (in package.json) which was not available on github.

**Comment by ritz078** [comment]
I did it just for demo and I am not sure that it can be a right pattern so was just asking a question. If you like to know about the code of that its just an additional `postinstall` script

```
+ "postinstall" : "starring <your_package_name>"
```

**Comment by ritz078** [comment]
You can find [starring](https://github.com/ritz078/starring) on GitHub.
