### ISSUE TITLE
Why output gzipped size when I am not writing a gzip?

### ISSUE THREAD

**Issue by binarykitchen** [ritz078/rollup-plugin-filesize#16]
With my current rollup config I am not writing a gzip to the destination folder. But your plugin still displays gzip stats. Not necessary and confusing in my opinion. Can the plugin be smarter?

**Comment by ritz078** [comment]
It can be made optional.

**Comment by binarykitchen** [comment]
yeah please, that would be cool

**Comment by ritz078** [comment]
try v1.4.1 and set `showGzippedSize: false` in options.

**Comment by binarykitchen** [comment]
yeah @ritz078 it works, but the implementation could be better: there is no need to calculate gzipSize unnecessarily when it's not shown, see
https://github.com/ritz078/rollup-plugin-filesize/blob/2631329828025238c21bb81b37a7a8f0328f4d35/src/index.js#L34

add a conditional there ...

... plus the file is too wide, better break it at column 80 or so.

**Comment by ritz078** [comment]
Ya sure. I will do those when I have a bit of time. I just made a quick release for now so that it solves your problem.

**Comment by ritz078** [comment]
Done in 1.4.2

**Comment by binarykitchen** [comment]
Good boy :)
