### ISSUE TITLE
Perf issues on CI (travis)

### ISSUE THREAD

**Issue by Andarist** [ritz078/rollup-plugin-filesize#28]
Not sure what can be done to improve the situation, but when using rollup's `experimentalCodeSplitting` each generated chunk gets passed to this plugin (in our case its dozens of times) and this caused Travis to REALLY slow down due to too high memory usage or something. 

It went from 5 minutes to 19 minutes.

**Comment by diegohaz** [comment]
For reference: https://github.com/reakit/reakit/pull/170

**Comment by ritz078** [comment]
The issue might be that `terser` is taking a lot of time in minification. I will check.
