### ISSUE TITLE
package.json main is pointing to null

### ISSUE THREAD

**Issue by Havunen** [ritz078/rollup-plugin-filesize#3]
in package.json main field is pointing to "main": "dist/index.js",   but dist folder is not shipped with NPM in this plugin. 

using plugin fails with following exception:
```
Error: Cannot find module 'rollup-plugin-filesize'
```

usage:
```javascript
import filesize from 'rollup-plugin-filesize';
```

ps. It was working fine few days ago

**Comment by ritz078** [comment]
I hope this has been resolved.

**Comment by Havunen** [comment]
works fine now.
