### ISSUE TITLE
Upgrade rollup to 1.0.0?

### ISSUE THREAD

**Issue by fralonra** [ritz078/rollup-plugin-filesize#34]
Rollup has just released v1.0.0, and it gave me the following warning:
```
(!) filesize plugin: The ongenerate hook used by plugin filesize is deprecated. The generateBundle hook should be used instead.
```

Consider upgrading rollup to v1.0.0 and using the new hook?

**Comment by ritz078** [comment]
Give me some time. :)
In case you want a quick fix, a PR is always welcome. Should be very easy.

**Comment by fralonra** [comment]
I have already submited a PR. Does the `yarn.lock` need to be commited?

**Comment by ritz078** [comment]
yes. :)

**Comment by fralonra** [comment]
Done!

**Comment by ritz078** [comment]
released as v6
