### ISSUE TITLE
`rollup-plugin-filesize` requires node-gyp to install

### ISSUE THREAD

**Issue by dosentmatter** [ritz078/rollup-plugin-filesize#52]
My CICD that uses a node docker image to build is failing on install because `rollup-plugin-filesize` depends on `brotli-size@0.1.0` which uses `iltorb` -> node-gyp. node-gyp requires python, make, and C/C++ compiler.

It would be nice if `rollup-plugin-filesize` works on a node-only machine.

Latest `brotli-size` uses native `brotli` library of `node >= 10.16`. So one option is to update `brotli-size` dependency.

Another option is to move `brotli-size` dependency to `optionalDependencies` since it's an optional feature of this plugin. That way `npm install` won't fail when `brotli-size` fails node-gyp dependencies.

I posted more info on [#33](https://github.com/ritz078/rollup-plugin-filesize/issues/33#issuecomment-509520118), but haven't gotten an answer.
My current workaround is to use `rollup-plugin-filesize@2.0.0`, before #22 added `brotli-size` as a dependency.

**Comment by ritz078** [comment]
sorry for the delay. should be fixed on 6.2.0

**Comment by dosentmatter** [comment]
Thanks for addressing this issue! Perhaps you should clarify in README that `showBrotliSize` requires `node >= 10.16` now. I think that's a better requirement than node-gyp.
