### ISSUE TITLE
(!) Accessing "isAsset" on files in the bundle is deprecated, please use "type === 'asset'" instead

### ISSUE THREAD

**Issue by photonstorm** [ritz078/rollup-plugin-filesize#57]
I get this warning spammed to the console (once for every file in my bundle) when using this plugin and Rollup 2.0.6. The fix appears quite easy in the source, but may break backward compatibility?

**Comment by kimulaco** [comment]
I looked into this issue.
rollup@1.20.0 or under there was no `type` property. So, I created the PR leaving the fallback. https://github.com/ritz078/rollup-plugin-filesize/pull/59
