### ISSUE TITLE
8.0.0 crashes with 'Cannot find module boxen.js'

### ISSUE THREAD

**Issue by photonstorm** [ritz078/rollup-plugin-filesize#71]
I have been using this plugin happily for ages. Noticed there was 8.0.0 available, so upgraded and now the plugin throws this error when building:

```
./dev/index.ts → ./dev/dist/index.js...
(node:16660) ExperimentalWarning: The fs.promises API is experimental
[!] (plugin filesize) Error: Cannot find module '/D:/wamp/www/phaser-genesis/node_modules/rollup-plugin-filesize/dist/reporters/boxen.js'
Error: Cannot find module '/D:/wamp/www/phaser-genesis/node_modules/rollup-plugin-filesize/dist/reporters/boxen.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at D:\wamp\www\phaser-genesis\node_modules\rollup-plugin-filesize\src\index.js:125:12
    at new Promise (<anonymous>)
    at map (D:\wamp\www\phaser-genesis\node_modules\rollup-plugin-filesize\src\index.js:125:12)
    at Array.map (<anonymous>)
    at getLoggingData (D:\wamp\www\phaser-genesis\node_modules\rollup-plugin-filesize\src\index.js:121:15)
    at Promise.all.Object.keys.map.filter.map.currentBundle (D:\wamp\www\phaser-genesis\node_modules\rollup-plugin-filesize\src\index.js:158:14)
```

This is with node v10.16.0 and Rollup 2.7.6 on Windows 10.

Downgrading to filesize 7.0.0 works fine.

**Comment by ritz078** [comment]
@brettz9 any idea why this might be happening ?

**Comment by brettz9** [comment]
@photonstorm , it would be helpful to know...does `D:/wamp/www/phaser-genesis/node_modules/rollup-plugin-filesize/dist/reporters/boxen.js` exist on your system?

I have a PR ready to submit that may fix that, but as it involves some speculation, it'd be helpful to know first if that file exists.

**Comment by maktarsis** [comment]
@brettz9 exists

I'm experiencing this issue on my windows laptop, though it works fine on my mac

so, I checked file location on my windows laptop and it is there

**Comment by brettz9** [comment]
Ok, if someone could:

1. Add this line (line 35 on `dist/index.js`, before `function filesize(...`):
````js
const isWindows = process.platform === "win32";
```
2. Change this block (i.e., lines 124-134 in `dist/index.js`--the `if`/`else` block beginning with `if (reporter === "boxen") {`):

```js
if (reporter === "boxen") {
          p = new Promise(function (resolve) { resolve(_interopNamespace(require( // Node should be ok with this, but transpiling
          //  to `require` doesn't work, so detect Windows
          //  to remove slash instead
          // "file://" +
          path.dirname(new URL((typeof document === 'undefined' ? new (require('u' + 'rl').URL)('file:' + __filename).href : (document.currentScript && document.currentScript.src || new URL('index.js', document.baseURI).href))).pathname).slice( // istanbul ignore next
          isWindows ? 1 : 0) + "/reporters/boxen.js"))); });
        } else {
          p = new Promise(function (resolve) { resolve(_interopNamespace(require( // Node should be ok with this, but transpiling
          //  to `require` doesn't work, so detect Windows
          //  to remove slash instead
          // "file://" +
          path.resolve(process.cwd(), reporter).slice( // istanbul ignore next
          isWindows ? 1 : 0)))); });
        }
```

That is the compiled result one should get with my file, and which I expect should work on Windows.

(This particular approach shouldn't be necessary if we were using ESM directly and weren't transpiling, but it makes sense to me now that it is needed with Windows and transpiling.)

**Comment by maktarsis** [comment]
> Ok, if someone could:
> 
> 1. Add this line (line 35 on `dist/index.js`, before `function filesize(...`):
> 
> ```js
> const isWindows = process.platform === "win32";
> ```
> 
> 1. Change this block (i.e., lines 124-134 in `dist/index.js`--the `if`/`else` block beginning with `if (reporter === "boxen") {`):
> 
> ```js
>         if (reporter === "boxen") {
>           p = new Promise(function (resolve) { resolve(_interopNamespace(require( // Node should be ok with this, but transpiling
>           //  to `require` doesn't work, so detect Windows
>           //  to remove slash instead
>           // "file://" +
>           path.dirname(new URL((typeof document === 'undefined' ? new (require('u' + 'rl').URL)('file:' + __filename).href : (document.currentScript && document.currentScript.src || new URL('index.js', document.baseURI).href))).pathname).slice( // istanbul ignore next
>           isWindows ? 1 : 0) + "/reporters/boxen.js"))); });
>         } else {
>           p = new Promise(function (resolve) { resolve(_interopNamespace(require( // Node should be ok with this, but transpiling
>           //  to `require` doesn't work, so detect Windows
>           //  to remove slash instead
>           // "file://" +
>           path.resolve(process.cwd(), reporter).slice( // istanbul ignore next
>           isWindows ? 1 : 0)))); });
>         }
> ```
> 
> That is the compiled result one should get with my file, and which I expect should work on Windows. The [source](https://github.com/ritz078/rollup-plugin-filesize/pull/72/files#diff-1fdf421c05c1140f6d71444ea2b27638) is cleaner.
> 
> (This particular approach shouldn't be necessary if we were using ESM directly and weren't transpiling, but it makes sense to me now that it is needed with Windows and transpiling.)

I just checked it on my windows laptop
can confirm it works

**Comment by brettz9** [comment]
Excellent thanks!
