### ISSUE TITLE
SourceMap support

### ISSUE THREAD

**Issue by thisconnect** [ritz078/rollup-plugin-filesize#8]
Hi, thanks for this nice plugin I like it a lot. But if it is enabled in `plugins` the sourcemaps a gone.

Sourcemaps with filesize:
```
{"version":3,"file":null,"sources":[],"sourcesContent":[],"names":[],"mappings":""}
```

Without filesize the sourcemaps are working fine.

**Comment by ritz078** [comment]
can you create a repo with minimal code to reproduce this ? I remember this was fixed earlier.

**Comment by thisconnect** [comment]
@ritz078 here you go https://github.com/thisconnect/test-rollup-filesize

Node.js v6.5.0

**Comment by ritz078** [comment]
cc @TrySound. How do i configure the plugin so that it returns the default sourcemap or the sourcemap returned from previous plugin ? I guess that's the error here.

**Comment by TrySound** [comment]
@ritz078 Why you return log in transformBundle? It can't be used anywhere.

**Comment by TrySound** [comment]
Also you may use ongenerate hook, which will be more semantically.

**Comment by ritz078** [comment]
can you point to any example based on that ?

**Comment by TrySound** [comment]
@ritz078 
```
ongenerate(bundle, { code }) {
  console.log(code);
}
```

**Comment by ritz078** [comment]
@thisconnect can u test with the latest release ?

**Comment by TrySound** [comment]
@thisconnect 0.5.4?

**Comment by TrySound** [comment]
Also you shoudn't return anything it ongenerate hook.

**Comment by ritz078** [comment]
okk. will fix this.

**Comment by ritz078** [comment]
done with 0.5.5

**Comment by thisconnect** [comment]
Thank you both!
