### ISSUE TITLE
0.4->0.5 broke my build

### ISSUE THREAD

**Issue by koresar** [ritz078/rollup-plugin-filesize#9]
After this commit the plugin does not print anything in my [project](http://github.com/stampit-org/stampit) :
https://github.com/ritz078/rollup-plugin-filesize/commit/750583bc214abe9e2624f23bfd7b47a83e131885 

I assume this should have been a Major update 0.4->1.0.

Please, republish as 1.0.

And thank you for the awesome plugin!

**Comment by ritz078** [comment]
published as 1.0.0

**Comment by koresar** [comment]
Thank you very much!
